[workspace]
resolver = "2"

members = [
    "value-traits-derive",
    "value-traits",
]

[workspace.dependencies]
value-traits = {path = "./value-traits" }
value-traits-derive = {path = "./value-traits-derive", version = "0.2.1" }
